# Stock market prediction using Linear Regression

In [14]:
import numpy as np
import pandas as pd

In [15]:
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [17]:
df=pd.read_csv(r"C:\Users\91801\Desktop\Stock market pred\archive (1)\infolimpioavanzadoTarget.csv")

C:\Users\91801\AppData\Local\Temp\ipykernel_13016\2916533218.py:1: DtypeWarning:

Columns (58,61,64,67,70,95,96,97,98,101,105,106,107,108,109,110,111,112,113,119,122,123,124,125,128,131,132,133,134,135,136,137,138,139,140,141,142,143,146,149,150,151,152,155,158,159,160,161,162,163,164,165,166,167,168,169,170,173,176,177,178,179,182,185,186,187,188,189,190,191,192,193,194,195,196,197,200,203,204,205,206,209,212,213,214,215,216,217,218,219,220,221,222,223,224,227,230,231,232,233,236,239,240,241,242,243,244,245,246,247,248,249,250,251,254,257,258,259,260,263,266,267,268,269,270,271,272,273,274,275,276,277,278,284,285,286,287,290,294,295,296,297,298,299,300,301,302,308,311,312,313,314,317,320,321,322,323,324,325,326,327,328,329,330,331,332,335,338,339,340,341,344,347,348,349,350,351,352,353,354,355,356,357,358,359,362,365,366,367,368,371,374,375,376,377,378,379,380,381,382,383,384,385,386,389,392,393,394,395,398,401,402,403,404,405,406,407,408,409,410,411,412,413,416,419,420,421,422,425,428,429,430,431,432,433,434,435,436,437,438,439,440,443,446,447,448,449,452,455,456,457,458,459,460,461,462,463,464,465,466,467,473,474,475,476,479,483,484,485,486,487,488,489,490,491,497,500,501,502,503,506,509,510,511,512,513,514,515,516,517,518,519,520,521,524,527,528,529,530,533,536,537,538,539,540,541,542,543,544,545,546,547,548,551,554,555,556,557,560,563,564,565,566,567,568,569,570,571,572,573,574,575,578,581,582,583,584,587,590,591,592,593,594,595,596,597,598,599,600,601,602,605,608,609,610,611,614,617,618,619,620,621,622,623,624,625,626,627,628,629,632,635,636,637,638,641,644,645,646,647,648,649,650,651,652,653,654,655,656,662,663,664,665,668,672,673,674,675,676,677,678,679,680,686,689,690,691,692,695,698,699,700,701,702,703,704,705,706,707,708,709,710,713,716,717,718,719,722,725,726,727,728,729,730,731,732,733,734,735,736,737,740,743,744,745,746,749,752,753,754,755,756,757,758,759,760,761,762,763,764,767,770,771,772,773,776,779,780,781,782,783,784,785,786,787,788,789,790,791,794,797,798,799,800,803,806,807,808,809,810,811,812,813,814,815,816,817,818,821,824,825,826,827,830,833,834,835,836,837,838,839,840,841,842,843,844,845,851,852,853,854,857,861,862,863,864,865,866,867,868,869,875,878,879,880,881,884,887,888,889,890,891,892,893,894,895,896,897,898,899,902,905,906,907,908,911,914,915,916,917,918,919,920,921,922,923,924,925,926,929,932,933,934,935,938,941,942,943,944,945,946,947,948,949,950,951,952,953,956,959,960,961,962,965,968,969,970,971,972,973,974,975,976,977,978,979,980,983,986,987,988,989,992,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1010,1013,1014,1015,1016,1019,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1040,1041,1042,1043,1046,1050,1051,1052,1053,1054,1055,1056,1057,1058,1098,1110,1116,1234,1235,1246,1247,1248,1249,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259) have mixed types. Specify dtype option on import or set low_memory=False.

In [18]:
df

,date,open,high,low,close,adjclose,volume,ticker,RSIadjclose15,RSIvolume15,...,high-15,K-15,D-15,stochastic-k-15,stochastic-d-15,stochastic-kd-15,volumenrelativo,diff,INCREMENTO,TARGET
0,03-01-2022,17.799999,18.219000,17.500000,17.760000,17.760000,106600,ASLE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.919758,-1.900001,-9.664295,0
1,04-01-2022,17.700001,18.309999,17.620001,17.660000,17.660000,128700,ASLE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.110440,-1.379999,-7.247895,0
2,05-01-2022,17.580000,17.799999,16.910000,16.950001,16.950001,103100,ASLE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.889560,-0.930000,-5.201344,0
3,06-01-2022,16.650000,16.879999,16.139999,16.170000,16.170000,173600,ASLE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.497843,-0.360000,-2.177856,0
4,07-01-2022,16.219999,16.290001,15.630000,15.710000,15.710000,137800,ASLE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.188956,-0.120000,-0.758054,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7776,23-12-2022,23.250000,23.540001,23.250000,23.290001,22.699928,4900,ATLO,60.782255,47.081752,...,23.600000,26.223672,27.022465,26.223672,27.022465,-0.798793,0.333333,NaN,NaN,0
7777,27-12-2022,23.350000,23.610001,23.250000,23.350000,22.758406,9200,ATLO,62.022801,47.747952,...,23.610001,30.764722,28.003602,30.764722,28.003602,2.761119,0.625850,NaN,NaN,0
7778,28-12-2022,23.450001,23.570000,23.219999,23.350000,22.758406,15200,ATLO,62.022801,48.713225,...,23.610001,30.764722,29.251039,30.764722,29.251039,1.513683,1.034014,NaN,NaN,0
7779,29-12-2022,23.330000,23.740000,23.330000,23.610001,23.011820,7100,ATLO,67.186408,47.445460,...,23.740000,46.457382,35.995609,46.457382,35.995609,10.461773,0.482993,NaN,NaN,0
7780,30-12-2022,23.680000,23.760000,23.610001,23.610001,23.011820,7100,ATLO,67.186408,47.445460,...,23.760000,45.784072,41.002059,45.784072,41.002059,4.782013,0.482993,NaN,NaN,0

In [19]:
df.shape

(7781, 1285)

In [20]:
df.isnull().sum()

date                  0
open                  0
high                  0
low                   0
close                 0
                   ...
stochastic-kd-15    587
volumenrelativo     215
diff                155
INCREMENTO          155
TARGET                0
Length: 1285, dtype: int64

In [21]:
df.dropna()

,date,open,high,low,close,adjclose,volume,ticker,RSIadjclose15,RSIvolume15,...,high-15,K-15,D-15,stochastic-k-15,stochastic-d-15,stochastic-kd-15,volumenrelativo,diff,INCREMENTO,TARGET
98,24-05-2022,13.810000,14.120000,13.610000,14.100000,14.100000,74700,ASLE,47.575179,48.098729,...,15.09,57.142875,47.186159,57.142875,47.186159,9.956716,0.644521,-0.060000,-0.423732,0
99,25-05-2022,14.100000,14.320000,14.050000,14.180000,14.180000,71400,ASLE,48.459097,47.832464,...,14.76,70.707082,59.066871,70.707082,59.066871,11.640211,0.616048,0.210000,1.503221,0
100,26-05-2022,14.120000,14.347000,13.790000,13.820000,13.820000,89700,ASLE,44.815889,49.493682,...,14.76,52.525237,60.125065,52.525237,60.125065,-7.599827,0.773943,0.510000,3.831707,0
101,27-05-2022,14.010000,14.250000,13.940000,14.110000,14.110000,84800,ASLE,48.178500,49.045623,...,14.76,67.171696,63.468005,67.171696,63.468005,3.703691,0.731665,0.060000,0.427049,0
102,31-05-2022,14.140000,14.140000,13.530000,13.860000,13.860000,315400,ASLE,45.611408,65.015137,...,14.76,52.127632,57.274855,52.127632,57.274855,-5.147223,2.721311,0.750000,5.720824,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7771,16-12-2022,22.700001,22.879999,22.500000,22.670000,22.095634,13800,ATLO,45.827378,48.222673,...,23.60,-26.417248,-17.134822,-26.417248,-17.134822,-9.282426,0.938776,0.604294,2.811801,0
7772,19-12-2022,22.600000,22.799999,22.379999,22.600000,22.027409,144600,ATLO,44.016221,69.143430,...,23.60,-28.900837,-23.695948,-28.900837,-23.695948,-5.204889,9.836735,0.730997,3.432489,0
7773,20-12-2022,22.600000,23.000000,22.600000,22.840000,22.261328,21000,ATLO,51.113614,49.069797,...,23.60,-9.727156,-21.681747,-9.727156,-21.681747,11.954591,1.428571,0.497078,2.283919,0
7774,21-12-2022,22.889999,23.389999,22.889999,23.309999,22.719419,9600,ATLO,61.385254,47.701266,...,23.60,27.821310,-3.602228,27.821310,-3.602228,31.423537,0.653061,0.292400,1.303786,0
7775,22-12-2022,23.330000,23.379999,23.049999,23.299999,22.709673,9900,ATLO,61.092635,47.742359,...,23.60,27.022413,15.038856,27.022413,15.038856,11.983557,0.673469,0.302147,1.348417,0

## Import Plotly Graph 
### Use it to plot every single data with full information

In [22]:
import plotly.graph_objects as go

In [23]:
fig = go.Figure(data=go.Ohlc(x=df['date'],
                open=df['open'],
                high=df['high'],
                low=df['low'],
                close=df['close']))
fig.update(layout_xaxis_rangeslider_visible=False)
fig.show()

### In this graph produced by plotly, the red stock indicates Bearish and the green stocks indicate bullish. If the curser is taken on top of any green or red point, it would provide the full details(date,open,high,low,close) of that particular stock

In [24]:
df.describe()

,open,high,low,close,adjclose,volume,RSIadjclose15,RSIvolume15,RSIadjclose25,RSIvolume25,...,high-15,K-15,D-15,stochastic-k-15,stochastic-d-15,stochastic-kd-15,volumenrelativo,diff,INCREMENTO,TARGET
count,7781.000000,7781.000000,7781.000000,7781.000000,7781.000000,7.781000e+03,7316.000000,7316.000000,7006.000000,7006.000000,...,7347.000000,7262.000000,7194.000000,7262.000000,7194.000000,7194.000000,7566.000000,7626.000000,7626.000000,7781.000000
mean,34.990220,35.655999,34.301243,34.964414,34.483147,7.586022e+05,46.817434,49.814790,46.966016,49.898659,...,37.947291,18.673824,18.704812,18.673824,18.704812,0.298413,inf,-0.259186,-2.674224,0.183010
std,99.841502,101.451058,98.073945,99.790823,98.603879,3.934491e+06,11.672838,5.002664,8.760961,3.420371,...,107.340294,75.723295,74.210933,75.723295,74.210933,14.661948,NaN,7.334250,268.268134,0.386699
min,0.410000,0.435000,0.405000,0.408000,0.408000,0.000000e+00,6.837461,35.303213,17.693637,39.520876,...,0.510000,-668.212635,-626.263336,-668.212635,-626.263336,-211.219036,0.000000,-90.538818,-23399.465950,0.000000
25%,4.050000,4.130000,3.980000,4.030000,3.960000,1.080000e+04,38.946316,47.182234,40.954487,48.266978,...,4.565000,6.153839,8.336837,6.153839,8.336837,-6.585432,0.637237,-0.417873,-4.494383,0.000000
50%,10.080000,10.110000,10.005000,10.080000,10.061000,8.406000e+04,46.259711,48.356834,46.459477,48.961162,...,10.640000,28.484828,28.478797,28.484828,28.478797,0.000000,1.000000,-0.025000,-0.304004,0.000000
75%,24.350000,24.500000,24.080000,24.250000,22.466007,6.724000e+05,54.061089,50.902284,52.289893,50.527067,...,25.170000,59.688404,58.664021,59.688404,58.664021,6.726947,1.655385,0.240000,2.812552,0.000000
max,795.739990,799.359985,784.960022,797.489990,783.376221,1.615550e+08,96.365095,99.622735,91.023108,97.782293,...,799.359985,100.000000,100.000000,100.000000,100.000000,198.156313,inf,120.256775,425.000000,1.000000

In [25]:
# Split the data into features (X) and target variable (y)
X = df[['open', 'high', 'low','volume']]
y = df['close']  # Close price will be the target variable to predict

In [26]:
X

           open       high        low  volume
0     17.799999  18.219000  17.500000  106600
1     17.700001  18.309999  17.620001  128700
2     17.580000  17.799999  16.910000  103100
3     16.650000  16.879999  16.139999  173600
4     16.219999  16.290001  15.630000  137800
...         ...        ...        ...     ...
7776  23.250000  23.540001  23.250000    4900
7777  23.350000  23.610001  23.250000    9200
7778  23.450001  23.570000  23.219999   15200
7779  23.330000  23.740000  23.330000    7100
7780  23.680000  23.760000  23.610001    7100

[7781 rows x 4 columns]

In [27]:
y

0       17.760000
1       17.660000
2       16.950001
3       16.170000
4       15.710000
          ...
7776    23.290001
7777    23.350000
7778    23.350000
7779    23.610001
7780    23.610001
Name: close, Length: 7781, dtype: float64

In [28]:
# Splitig  the data into 80% training data  and 20% testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [29]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [30]:
model.score(X_train,y_train)

0.9998910905299335

### This means that the training is 99% accuarate

In [31]:
y_pred = model.predict(X_test)

In [32]:
model.score(X_test,y_test)

0.9998775893267019

### The test is also 99% accurate

In [33]:
mse = mean_squared_error(y_test,y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 1.035051588565217

### The Mean Squared Error is also very Less

In [34]:
a=pd.read_csv(r"C:\Users\91801\Desktop\Stock market pred\TATASTEEL.csv")
a

           date    open    high     low   volume company
0    01-01-2023  148.00  153.20  146.10  2003185   TISCO
1    02-01-2023  150.10  153.00  143.05  1555136   TISCO
2    03-01-2023  144.60  162.90  144.60  3840284   TISCO
3    04-01-2023  158.95  169.10  158.95  2560449   TISCO
4    05-01-2023  173.40  179.00  166.30  3641691   TISCO
..          ...     ...     ...     ...      ...     ...
360  27-12-2023  132.70  133.65  131.80   961461   TISCO
361  28-12-2023  132.10  133.50  131.50  1468699   TISCO
362  29-12-2023  132.50  132.80  129.60  1203417   TISCO
363  30-12-2023  129.55  130.00  127.80  1461999   TISCO
364  31-12-2023  127.55  127.90  123.55  1246912   TISCO

[365 rows x 6 columns]

In [35]:
a.shape

(365, 6)

In [36]:
a.isnull().sum()

date       0
open       0
high       0
low        0
volume     0
company    0
dtype: int64

In [37]:
a=a.dropna()
a

           date    open    high     low   volume company
0    01-01-2023  148.00  153.20  146.10  2003185   TISCO
1    02-01-2023  150.10  153.00  143.05  1555136   TISCO
2    03-01-2023  144.60  162.90  144.60  3840284   TISCO
3    04-01-2023  158.95  169.10  158.95  2560449   TISCO
4    05-01-2023  173.40  179.00  166.30  3641691   TISCO
..          ...     ...     ...     ...      ...     ...
360  27-12-2023  132.70  133.65  131.80   961461   TISCO
361  28-12-2023  132.10  133.50  131.50  1468699   TISCO
362  29-12-2023  132.50  132.80  129.60  1203417   TISCO
363  30-12-2023  129.55  130.00  127.80  1461999   TISCO
364  31-12-2023  127.55  127.90  123.55  1246912   TISCO

[365 rows x 6 columns]

In [38]:
X_new = a[['open', 'high', 'low','volume']]

In [39]:
y_new = model.predict(X_new)

In [40]:
Final = a
Final["close"]=y_new

In [41]:
Final

           date    open    high     low   volume company       close
0    01-01-2023  148.00  153.20  146.10  2003185   TISCO  150.848594
1    02-01-2023  150.10  153.00  143.05  1555136   TISCO  146.580837
2    03-01-2023  144.60  162.90  144.60  3840284   TISCO  160.214143
3    04-01-2023  158.95  169.10  158.95  2560449   TISCO  167.642016
4    05-01-2023  173.40  179.00  166.30  3641691   TISCO  172.147257
..          ...     ...     ...     ...      ...     ...         ...
360  27-12-2023  132.70  133.65  131.80   961461   TISCO  132.782944
361  28-12-2023  132.10  133.50  131.50  1468699   TISCO  132.822402
362  29-12-2023  132.50  132.80  129.60  1203417   TISCO  130.316322
363  30-12-2023  129.55  130.00  127.80  1461999   TISCO  128.477713
364  31-12-2023  127.55  127.90  123.55  1246912   TISCO  124.463442

[365 rows x 7 columns]

In [42]:
Final.to_csv(r"C:\Users\91801\Downloads\predicted_close.csv")

In [43]:
fig = go.Figure(data=go.Ohlc(x=Final['date'],
                open=Final['open'],
                high=Final['high'],
                low=Final['low'],
                close=Final['close']))
fig.update(layout_xaxis_rangeslider_visible=False)
fig.show()

### This is the OHLC curve of the predicted dataset. The green ones are again Bullish in nature and the red one are bearish